train: ../train/images
val: ../valid/images
test: ../test/images

nc: 2
names: ['cat', 'dog']

optimizer:
  type: adamw
  lr: 0.001

roboflow:
  workspace: uni-lmndf
  project: assignment_2-87kxj
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/uni-lmndf/assignment_2-87kxj/dataset/1